### ISSUE TITLE
No Docs Generated

### ISSUE THREAD

**Issue by ghost** [krampstudio/grunt-jsdoc#79]
Currently running grunt-jsdoc against the following file, produces the Index, that includes my README and then produces a file called ujumbe.js.html, that contains the source code but, no documentation is generated from the source.

https://github.com/ossreleasefeed/ujumbe/blob/master/js/ujumbe.js

From what I can see and having read over the JSDoc documentation, my doc comments looks fine, the task completes fine with no errors, but alas, no docs are being generated.

Here is my Grunt file:

https://github.com/ossreleasefeed/ujumbe/blob/master/Gruntfile.js

**Comment by mmaelzer** [comment]
Something worth noting (that I just spent an hour or so debugging) is that by default, jsdoc will not process files inside a folder that starts with an underscore; e.g. `jsdoc -r _src/` will generate empty docs since `_src` starts with an underscore. To troubleshoot this and other empty output issues, use the jsdoc CLI and pass the `-X` flag to see what files jsdoc plans to process.

**Comment by mmaelzer** [comment]
I was just reminded that I never provided a solution to this for those that still encounter the problem. In the root of your project directory, drop a `jsdoc.conf` file with the following content:
```javascript
{
    "source": {
        "includePattern": ".+\\.js(doc)?$",
        "excludePattern": ""
    }
}
```
